name = "motionpluplus_example_config"

[[wiimote]]
ID = 2

[wiimote.buttons]
map_to = "keyboard"
a = "KEY_W"
b = "KEY_E"
right = "KEY_RIGHT"
left = "KEY_LEFT"
up = "KEY_UP"
down = "KEY_DOWN"
plus = "KEY_KPPLUS"
minus = "KEY_KPMINUS"
home = "KEY_HOME"
one = "KEY_1"
two = "KEY_2"

[wiimote.accel]
map_to = "keyboard"
x.key = "KEY_X"
x.trigger = 0.5                     # Force to trigger key.
x.trigger_direction = "+"     # "+" or "-" or "+/-"
y.key = "KEY_Y"
y.trigger = 0.4
z.key = "KEY_Z"
z.trigger = 0.65

